### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by BenStrachan** [BenStrachan/one_page#4]
BD darkness 
- bg-darkness in custom style sheet 
- please add this filter to hero image 

General improvement 
- responsiveness hero section 
- button responsiveness, it seperates on small screen 
- I think text is hard to see

**Comment by chutuan** [comment]
@BenStrachan 
![screenshot from 2018-01-14 11-41-42](https://user-images.githubusercontent.com/8140820/34912905-f09d6596-f91f-11e7-81a5-80ad8d9c0c0a.png)
